name: Build RyujinxApp

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-12
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build with CI build script
      run: ./scripts/ci_build.sh

    - name: Upload build output
      uses: actions/upload-artifact@v1
      with:
        name: RyujinxApp
        path: ipa_make/RyujinxApp.ipa
